name: Python Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use the recommended version

    - name: Set up Python
      uses: actions/setup-python@v5 # Use the recommended version
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install dependencies
      run: |
        cd search
        python -m pip install --upgrade pip
        pip install pytest # Install pytest

    - name: Run tests with pytest
      run: |
        python -m pytest
